<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error ocurred deleting your file' => 'Ocurrió un error al borrar su avatar',
    'Remove' => 'Quitar',
    'Remove avatar permanently? This can not be undone.' => 'Quitar el avatar permanentemente?',
    'A problem ocurred uploading your picture. Contact administrator' => 'Ocurrió un problema al cargar su imagen. Contacte por favor con el administrador',
    'Change' => 'Cambiar',
];
